version: '3'
services:
    web:
        build: web
    proxy:
        build: proxy
        ports:
        - "8081:80"
    psql:
        #build: psql
        image: postgres
        ports: 
        - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'admin123'
            POSTGRES_DB: 'guests'
        volumes:
        - ./psql/:/docker-entrypoint-initdb.d
            